slogan: "Hacking registers and bits."

theme: bootstrap
inverse: true

menu:
  - title: 归档
    url: archives/
    intro: "所有的文章。"
    icon: "fa fa-archive"
  - title: 分类
    url: categories/
    intro: "所有的分类。"
    icon: "fa fa-folder"
  - title: 标签
    url: tags/
    intro: "所有的标签。"
    icon: "fa fa-tags"
  - title: 关于
    url: about/
    intro: "关于。"
    icon: "fa fa-user"

links:
  - title: "古作坊 Agu's Mill"
    url: https://aguegu.github.io
    intro: "aguegu的博客。"
    icon: "fa fa-globe"
  - title: "稚晖的个人站"
    url: http://www.pengzhihui.xyz/
    intro: pengzhihui的博客。
    icon: "fa fa-globe"
  - title: "CSK.Blog"
    url: http://www.csksoft.net/blog
    intro: CSKSOFT的博客。
    icon: "fa fa-globe"
  - title: "吴川斌的博客"
    url: https://www.mr-wu.cn/
    intro: 吴川斌的博客。
    icon: "fa fa-globe"
  - title: "Jiadai Sun的博客"
    url: https://sunjiadai.xyz/blog/
    intro: Jiadai Sun的博客。
    icon: "fa fa-globe"
  - title: "IAMLIUBO的博客"
    url: https://blogs.oopswow.com/
    intro: IAMLIUBO的博客。
    icon: "fa fa-globe"
  - title: "阿正的个人站"
    url: http://wenzheng.club/
    intro: 阿正的博客。
    icon: "fa fa-globe"

widgets:
  - search
  - category
  - tagcloud
  - recent_posts
  - links
  # - recent_comments

rss:
fancybox: true
favicon: images/favicon/favicon.ico
duoshuo_shortname:

# Analytics
google_analytics:
  enable: true
  siteid: UA-110461716-1
baidu_tongji:
  enable: true
  siteid: eac960348a384b717470a4acab997cbc

# Search
swiftype_key:

# Share widgets
bdshare: false
jiathis: false

# Built-in comment system
comment_js:
  enable: true
  type: "github"
  user: "myyerrol"
  repo: "myyerrol_website_comment"
  client_id: "95098d084621006b4f69"
  client_secret: "72389de7182c8b4ecf69363b316da57baf407432"
  count: 15

# MathJax
mathjax:
  enable: true

# Valine
valine:
  enable: true
  appId: "QMYiREeDi9SFmzTzPKVuVDTc-gzGzoHsz"
  appKey: "HwMiVpt4CBq1GURHowK8u6JC"
  placeholder: "提交评论时请留下邮箱，收到回复后将自动通知"
  avatar: "robohash"
  page: 15
  enableQQ: true
  requiredFields: ["nick", "mail"]
